THIS DIDNT WORK I WAS TRYING TO FIND A WAY OF ADDING A FINDER OF CALORIES FUNCTION!!

 - Issues calories might be skewing the data as they are much bigger number, if so Soln maybe make calories x10^(-2)
 - item Maybe should we exclude calories from knn, I dont think so as its a good idicator of similar food thus useful

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn

In [2]:
data_clean = pd.read_pickle("./nutrition_data.pkl")
data_clean

name   Food Group  \
0      Pillsbury Golden Layer Buttermilk Biscuits Art...  Baked Foods   
1      Pillsbury Cinnamon Rolls With Icing Refrigerat...  Baked Foods   
2                Waffles Buttermilk Frozen Ready-To-Heat  Baked Foods   
3         Waffle Buttermilk Frozen Ready-To-Heat Toasted  Baked Foods   
4      Waffle Buttermilk Frozen Ready-To-Heat Microwaved  Baked Foods   
...                                                  ...          ...   
12197  Nutritional Drink Or Shake Ready-To-Drink Ligh...    Beverages   
12198  Nutritional Drink Or Shake High Protein Ready-...    Beverages   
12199  Nutritional Drink Or Shake High Protein Ready-...    Beverages   
12200  Nutritional Powder Mix (Kellogg's Special K20 ...   Baby Foods   
12201              Fluid Replacement 5% Glucose In Water    Beverages   

       Calories  Fat (g)  Protein (g)  Carbohydrate (g)  Sugars (g)  Fiber (g)  
0         307.0    13.24         5.88             41.18        5.88        1.2  
1         330.0    11.27         4.34             53.42       21.34        1.4  
2         273.0     9.22         6.58             41.05        4.30        2.2  
3         309.0     9.49         7.42             48.39        4.41        2.6  
4         289.0     9.40         6.92             44.16        4.50        2.4  
...         ...      ...          ...               ...         ...        ...  
12197      38.0     1.15         4.78              2.10        0.38        0.2  
12198      58.0     2.88         6.59              0.85        0.60        0.4  
12199      58.0     2.88         6.59              0.85        0.60        0.4  
12200     380.0     0.60        35.20             58.40        2.00       37.5  
12201      18.0     0.00         0.00              5.00        4.64        0.0  

[12202 rows x 8 columns]

## NOW DOING KNN

In [3]:
# y is the list of food groups 
y = data_clean.iloc[:, 1].values

# x is the labels and nutritional values (including calories)
X = data_clean.iloc[:, 2:].values

z = data_clean.iloc[:, 0]
c = data_clean.iloc[:, 2]

print(X)
print(y)
print(z)

[[307.    13.24   5.88  41.18   5.88   1.2 ]
 [330.    11.27   4.34  53.42  21.34   1.4 ]
 [273.     9.22   6.58  41.05   4.3    2.2 ]
 ...
 [ 58.     2.88   6.59   0.85   0.6    0.4 ]
 [380.     0.6   35.2   58.4    2.    37.5 ]
 [ 18.     0.     0.     5.     4.64   0.  ]]
['Baked Foods' 'Baked Foods' 'Baked Foods' ... 'Beverages' 'Baby Foods'
 'Beverages']
0        Pillsbury Golden Layer Buttermilk Biscuits Art...
1        Pillsbury Cinnamon Rolls With Icing Refrigerat...
2                  Waffles Buttermilk Frozen Ready-To-Heat
3           Waffle Buttermilk Frozen Ready-To-Heat Toasted
4        Waffle Buttermilk Frozen Ready-To-Heat Microwaved
                               ...                        
12197    Nutritional Drink Or Shake Ready-To-Drink Ligh...
12198    Nutritional Drink Or Shake High Protein Ready-...
12199    Nutritional Drink Or Shake High Protein Ready-...
12200    Nutritional Powder Mix (Kellogg's Special K20 ...
12201                Fluid Replacement 5% Glucos

In [4]:
# considered doing this but not necessary
# I dont think you need to do this as calories is a good indicator of the food item and we do not expect that people 
# will want to significantly change their calorie intake rather reduce it by a reasonable amount
# y is the list of food groups 
#y = data_clean.iloc[:, 1].values

# x is the labels and nutritional values (not including calories!!!) 
X2 = data_clean.iloc[:, 3:].values

print(X2)
print(y)

[[13.24  5.88 41.18  5.88  1.2 ]
 [11.27  4.34 53.42 21.34  1.4 ]
 [ 9.22  6.58 41.05  4.3   2.2 ]
 ...
 [ 2.88  6.59  0.85  0.6   0.4 ]
 [ 0.6  35.2  58.4   2.   37.5 ]
 [ 0.    0.    5.    4.64  0.  ]]
['Baked Foods' 'Baked Foods' 'Baked Foods' ... 'Beverages' 'Baby Foods'
 'Beverages']


In [5]:
import operator
from pprint import pprint #short for pretty print

def knn(X, y, test_point, k):
    distances = [] #empty list (keeping track of distances and class in a list)
    for i in range(len(X)):
        distance = np.linalg.norm(X[i] - test_point) #keeping track of the distances
        distances.append((y[i], X[i], distance)) #this keeps track of 
        #(name, label, data point, distance of that data point to that test point)
    
    distances.sort(key=operator.itemgetter(2)) #sort our list of distances by 4th element 
    #list of tuples, sorting a list of something more complicated than numbers
    #sorted distance with smallest distance at the top of the list.
    
    #now we want to find the most frequent label,(ie y[i]), in the k nearest neighbours
   
    nn_labels = [] #list to keep track of this
    for nn in distances[:k]: #iterate over first k distances (ie k smallest distances from testpoint)
        nn_labels.append(nn[0]) #append to list the label y[i] for element
        #iteration means in end we get a list of labels of each element in these first k distances
    
    from statistics import mode
    y_hat = mode(nn_labels) #most common element of this list 
    #ie most common label for the the k nearest neighbours
    
    
    print("Test point: for",test_point_food_item, "is" +str(test_point))
    print("Closest K neighbours")
    pprint(distances[:k]) #using pprint to print clearer
    print("Furtherest K neighbours")
    pprint(distances[-k:]) #furthest k distances away, from -k to end of array
    
    return y_hat




In [6]:
#testing on data point to see if its catagorised right THIS NEEDS TO LINE UP
idx = 3000

test_point = X[idx]
test_point_label = y[idx]
test_point_food_item = z[idx]
test_point_calories = c[idx]

X = np.delete(X, idx, axis=0) 
z = np.delete(z, np.arange(idx)) NEEDS FIXING
c = data_clean.iloc[:, 2] NEEDS FIXING
#cardinal sin to train on testing set so delete this x from testing set X
#delete row from x so not training on dataset

In [7]:
elementname = data_clean.loc[idx]['name']
print(data_clean.loc[idx]['name'])
#or now could use print(test_point_food_item)

Chicken Broilers Or Fryers Meat Only Stewed


## finding substitute with least calories 
have to look at the calorie collumn and then find smallest 'c', but i cant do it

In [8]:
#test where now 
y_hat = knn(X, y, test_point, 3) #10 nearest neighbours
print("Prediction for", elementname,"is: "+str(y_hat))
print("Actual: "+str(y[idx]))

Test point: for Chicken Broilers Or Fryers Meat Only Stewed is[177.     6.71  27.29   0.     0.     0.  ]
Closest K neighbours
[('Meats',
  array([177.  ,   6.78,  27.12,   0.  ,   0.  ,   0.  ]),
  0.18384776310850076),
 ('Meats',
  array([177.  ,   6.48,  27.76,   0.  ,   0.  ,   0.  ]),
  0.5232590180780471),
 ('Meats',
  array([177.  ,   7.49,  27.51,   0.  ,   0.  ,   0.  ]),
  0.8104319835741933)]
Furtherest K neighbours
[('Baby Foods', array([900., 100.,   0.,   0.,   0.,   0.]), 729.5044675668546),
 ('Fats and Oils',
  array([902., 100.,   0.,   0.,   0.,   0.]),
  731.4866835424963),
 ('Fats and Oils',
  array([902., 100.,   0.,   0.,   0.,   0.]),
  731.4866835424963)]
Prediction for Chicken Broilers Or Fryers Meat Only Stewed is: Meats
Actual: Meats


In [8]:
import operator
from pprint import pprint #short for pretty print

def knn(X, y, z, c, test_point, k):
    distances = [] #empty list (keeping track of distances and class in a list)
    for i in range(len(X)):
        distance = np.linalg.norm(X[i] - test_point) #keeping track of the distances
        distances.append((y[i], z[i], c[i], X[i], distance)) #this keeps track of 
        #(name, label, data point, distance of that data point to that test point)
    
    distances.sort(key=operator.itemgetter(4)) #sort our list of distances by 4th element 
    #list of tuples, sorting a list of something more complicated than numbers
    #sorted distance with smallest distance at the top of the list.
    
    #now we want to find the most frequent label,(ie y[i]), in the k nearest neighbours
   
    nn_labels = [] #list to keep track of this
    for nn in distances[:k]: #iterate over first k distances (ie k smallest distances from testpoint)
        nn_labels.append(nn[0]) #append to list the label y[i] for element
        #iteration means in end we get a list of labels of each element in these first k distances
    
    from statistics import mode
    y_hat = mode(nn_labels) #most common element of this list 
    #ie most common label for the the k nearest neighbours
    
    
    print("Test point: for",test_point_food_item, "is" +str(test_point))
    print("Closest K neighbours")
    pprint(distances[:k]) #using pprint to print clearer
    print("Furtherest K neighbours")
    pprint(distances[-k:]) #furthest k distances away, from -k to end of array
    
    return y_hat




In [9]:
#test where now 
y_hat = knn(X, y, z, c, test_point, 3) #10 nearest neighbours
print("Prediction for", elementname,"is: "+str(y_hat))
print("Actual: "+str(y[idx]))

Test point: for Chicken Broilers Or Fryers Meat Only Stewed is[177.     6.71  27.29   0.     0.     0.  ]
Closest K neighbours
[('Meats',
  'Beef Round Knuckle Tip Center Steak Separable Lean And Fat Trimmed To 0 '
  'Inch Fat All Grades Raw',
  143.0,
  array([177.  ,   6.78,  27.12,   0.  ,   0.  ,   0.  ]),
  0.18384776310850076),
 ('Meats',
  'Beef Round Bottom Round Roast Separable Lean Only Trimmed To 0 Inch Fat All '
  'Grades Cooked Roasted',
  177.0,
  array([177.  ,   6.48,  27.76,   0.  ,   0.  ,   0.  ]),
  0.5232590180780471),
 ('Meats',
  'Beef Loin Top Loin Steak Boneless Lip Off Separable Lean Only Trimmed To 0 '
  'Inch Fat Choice Raw',
  149.0,
  array([177.  ,   7.49,  27.51,   0.  ,   0.  ,   0.  ]),
  0.8104319835741933)]
Furtherest K neighbours
[('Baby Foods',
  'Infant Formula Abbott Nutrition Similac Advance With Iron Liquid '
  'Concentrate Not Reconstituted',
  127.0,
  array([900., 100.,   0.,   0.,   0.,   0.]),
  729.5044675668546),
 ('Fats and Oils',
  'Be

In [12]:
def knnc(X, y, z, c, test_point, k): #z is items name c number of calories
    distances = [] #empty list (keeping track of distances and class in a list)
    for i in range(len(X)):
        distance = np.linalg.norm(X[i] - test_point) #keeping track of the distances
        distances.append((y[i], X[i], distance, c[i], z[i])) #this keeps track of 
        #(name, label, data point, distance of that data point to that test point)
    
    distances.sort(key=operator.itemgetter(2)) #sort our list of distances by 4th element 
    #list of tuples, sorting a list of something more complicated than numbers
    #sorted distance with smallest distance at the top of the list.
    
    #now we want to find the most frequent label,(ie y[i]), in the k nearest neighbours
   
    nn_labels = []
    #nn_calories = [] #list to keep track of this
    #nn_names = []
    for nn in distances[:k]: #iterate over first k distances (ie k smallest distances from testpoint)
        nn_labels.append([nn[0],nn[3],nn[4]])#append to list the label y[i] for element
        #nn_calories.append(nn[3])
        #nn_names.append(nn[4])
        #iteration means in end we get a list of labels of each element in these first k distances
    
    
    
    #y_hat = mode(nn_labels) #most common element of this list 
    #ie most common label for the the k nearest neighbours
    
    item_min_cal = min(nn_labels, key = lambda q:q[1])[2]
    
    print("Test point: for",test_point_food_item, "is" +str(test_point))
    print("Closest K neighbours")
    pprint(distances[:k]) #using pprint to print clearer
    
    
    return item_min_cal

In [10]:
#want to build a function that finds the smallest c???
def dist(X, y, z, c, test_point, k): #c is element of calories
    distances = [] #empty list (keeping track of distances and class in a list)
    for i in range(len(X)):
        distance = np.linalg.norm(X[i] - test_point) #keeping track of the distances
        distances.append((y[i], X[i], distance, z[i],c[i])) #this keeps track of 
        #(name, label, data point, distance of that data point to that test point, name element, calories of element)
    
    distances.sort(key=operator.itemgetter(2)) #sort our list of distances by 4th element 
    #list of tuples, sorting a list of something more complicated than numbers
    #sorted distance with smallest distance at the top of the list.
    
    #now we want to find the label with lowest calories,(ie z[i]), in the k nearest neighbours
   
    nn_labels = []
    #nn_calories = [] #list to keep track of this
    #nn_names = []
    for nn in distances[:k]: #iterate over first k distances (ie k smallest distances from testpoint)
        nn_labels.append([nn[0],nn[3],nn[4]])#append to list the label y[i] for element
        #nn_calories.append(nn[3])
        #nn_names.append(nn[4])
        #iteration means in end we get a list of labels of each element in these first k distances
    
    nn_low_cal = [] #list to keep track of this
   
    #for nn_labels: #iterate over first k distances (ie k smallest distances from testpoint)
        
    nn_labels.sort(key=operator.itemgetter(0)) #sort by first element in array ie calories
    print nn_labels(k) #print kth element of nn_labels once sorted biggest to smallest
    
            #want this step to find smallest 'c' out of these but cant work it out
        
    
    print("Test point: for",test_point_food_item, "is" +str(test_point))
    print("Closest K neighbours")
    pprint(distances[:k]) #using pprint to print clearer
    
    
    return nn_low_cal #neighbour with the lowest calories


In [13]:
#out of 10 nearest neighbours which one has lowest calories:
#smallest calories of closest k neighbours  
knnc(X, y, z, c, test_point, 5)



Test point: for Chicken Broilers Or Fryers Meat Only Stewed is[177.     6.71  27.29   0.     0.     0.  ]
Closest K neighbours
[('Meats',
  array([177.  ,   6.78,  27.12,   0.  ,   0.  ,   0.  ]),
  0.18384776310850076,
  143.0,
  'Beef Round Knuckle Tip Center Steak Separable Lean And Fat Trimmed To 0 '
  'Inch Fat All Grades Raw'),
 ('Meats',
  array([177.  ,   6.48,  27.76,   0.  ,   0.  ,   0.  ]),
  0.5232590180780471,
  177.0,
  'Beef Round Bottom Round Roast Separable Lean Only Trimmed To 0 Inch Fat All '
  'Grades Cooked Roasted'),
 ('Meats',
  array([177.  ,   7.49,  27.51,   0.  ,   0.  ,   0.  ]),
  0.8104319835741933,
  149.0,
  'Beef Loin Top Loin Steak Boneless Lip Off Separable Lean Only Trimmed To 0 '
  'Inch Fat Choice Raw'),
 ('Meats',
  array([176.  ,   6.42,  27.68,   0.  ,   0.  ,   0.  ]),
  1.1118453129819816,
  176.0,
  'Beef Round Tip Round Roast Separable Lean Only Trimmed To 0 Inch Fat Choice '
  'Cooked Roasted'),
 ('Meats',
  array([177.  ,   7.2 ,  26.22, 

'Beef Round Knuckle Tip Center Steak Separable Lean And Fat Trimmed To 0 Inch Fat All Grades Raw'