In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn

try:
    import openpyxl
except:
    get_ipython().system('pip install openpyxl')
    import openpyxl

In [2]:
data = pd.read_excel('https://www.myfooddata.com/spreadsheets/MyFoodData-Nutrition-Facts-SpreadSheet-Release-1-4.xlsx', header=3, usecols="B:I")

In [3]:
#removing the NANs from the dataset for food groups and other values
#data = data[data['Food Group'].notna()]
data_clean = data.dropna(subset=['Food Group', 'Protein (g)','Sugars (g)', 'Fiber (g)'])
data_clean

name   Food Group  \
0      Pillsbury Golden Layer Buttermilk Biscuits Art...  Baked Foods   
1      Pillsbury Cinnamon Rolls With Icing Refrigerat...  Baked Foods   
4                Waffles Buttermilk Frozen Ready-To-Heat  Baked Foods   
5         Waffle Buttermilk Frozen Ready-To-Heat Toasted  Baked Foods   
6      Waffle Buttermilk Frozen Ready-To-Heat Microwaved  Baked Foods   
...                                                  ...          ...   
14154  Nutritional Drink Or Shake Ready-To-Drink Ligh...    Beverages   
14155  Nutritional Drink Or Shake High Protein Ready-...    Beverages   
14156  Nutritional Drink Or Shake High Protein Ready-...    Beverages   
14157  Nutritional Powder Mix (Kellogg's Special K20 ...   Baby Foods   
14158              Fluid Replacement 5% Glucose In Water    Beverages   

       Calories  Fat (g)  Protein (g)  Carbohydrate (g)  Sugars (g)  Fiber (g)  
0         307.0    13.24         5.88             41.18        5.88        1.2  
1         330.0    11.27         4.34             53.42       21.34        1.4  
4         273.0     9.22         6.58             41.05        4.30        2.2  
5         309.0     9.49         7.42             48.39        4.41        2.6  
6         289.0     9.40         6.92             44.16        4.50        2.4  
...         ...      ...          ...               ...         ...        ...  
14154      38.0     1.15         4.78              2.10        0.38        0.2  
14155      58.0     2.88         6.59              0.85        0.60        0.4  
14156      58.0     2.88         6.59              0.85        0.60        0.4  
14157     380.0     0.60        35.20             58.40        2.00       37.5  
14158      18.0     0.00         0.00              5.00        4.64        0.0  

[12202 rows x 8 columns]

In [20]:
# y is the list of food groups 
y = data_clean.iloc[:, 1].values

# x is the labels and nutritional values 
X = data_clean.iloc[:, [0,2,3,4,5,6,7]].values

print(X)
print(y)

[['Pillsbury Golden Layer Buttermilk Biscuits Artificial Flavor Refrigerated Dough'
  307.0 13.24 ... 41.18 5.88 1.2]
 ['Pillsbury Cinnamon Rolls With Icing Refrigerated Dough' 330.0 11.27
  ... 53.42 21.34 1.4]
 ['Waffles Buttermilk Frozen Ready-To-Heat' 273.0 9.22 ... 41.05 4.3 2.2]
 ...
 ['Nutritional Drink Or Shake High Protein Ready-To-Drink Nfs' 58.0 2.88
  ... 0.85 0.6 0.4]
 ["Nutritional Powder Mix (Kellogg's Special K20 Protein Water)" 380.0
  0.6 ... 58.4 2.0 37.5]
 ['Fluid Replacement 5% Glucose In Water' 18.0 0.0 ... 5.0 4.64 0.0]]
['Baked Foods' 'Baked Foods' 'Baked Foods' ... 'Beverages' 'Baby Foods'
 'Beverages']


In [21]:
#Food_Groups = np.reshape(y, (-1, 1))
#Food_Groups

In [22]:
#inputting to encode but not used 
#Food_Group = (['American Indian', 'Baby Foods', 'Baked Foods', 'Beans and Lentils', 'Beverages', 'Breakfast Cereals','Dairy and Egg Products', 'Fast Foods', 'Fats and Oils', 'Fish', 'Fruits', 'Grains and Pasta', 'Meats', 'Nuts and Seeds', 'Prepared Meals', 'Restaurant Foods', 'Snacks', 'Soups and Sauces', 'Spices and Herbs', 'Sweets', 'Vegetables'])
#Food_Group

In [23]:
from sklearn import preprocessing

# like "importing the LabelEncoder as le"
# fitting the label encoder to y
le = preprocessing.LabelEncoder()
le.fit(y)

LabelEncoder()

In [24]:
# listing the different classes (i.e all the food groups) in y
Food_Groups = list(le.classes_)
Food_Groups

['American Indian',
 'Baby Foods',
 'Baked Foods',
 'Beans and Lentils',
 'Beverages',
 'Breakfast Cereals',
 'Dairy and Egg Products',
 'Dairy and Egg Products ',
 'Fast Foods',
 'Fats and Oils',
 'Fish',
 'Fruits',
 'Grains and Pasta',
 'Meats',
 'Nuts and Seeds',
 'Prepared Meals',
 'Restaurant Foods',
 'Snacks',
 'Soups and Sauces',
 'Spices and Herbs',
 'Sweets',
 'Vegetables']

In [25]:
# labelling all the food groups with numerical values
labels = le.transform(Food_Groups)
labels

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21])

In [26]:
# demonstrating how the numerical labels can be converted back to the original labels
list(le.inverse_transform(labels))

['American Indian',
 'Baby Foods',
 'Baked Foods',
 'Beans and Lentils',
 'Beverages',
 'Breakfast Cereals',
 'Dairy and Egg Products',
 'Dairy and Egg Products ',
 'Fast Foods',
 'Fats and Oils',
 'Fish',
 'Fruits',
 'Grains and Pasta',
 'Meats',
 'Nuts and Seeds',
 'Prepared Meals',
 'Restaurant Foods',
 'Snacks',
 'Soups and Sauces',
 'Spices and Herbs',
 'Sweets',
 'Vegetables']

In [27]:
# here is our y values, our original Food Group column has been converted to the numerical labels 
y = le.transform(y)
y

array([2, 2, 2, ..., 4, 1, 4])

# Implementing Nearest Neighbours algorithm


In [53]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [57]:
print(X_train)
print(y_train)

[['Chicken Leg Drumstick And Thigh Ns As To Cooking Method Skin Eaten'
  218.0 13.63 ... 0.12 0.12 0.0]
 ['Bread Reduced-Calorie White' 207.0 2.5 ... 44.3 4.76 9.7]
 ['Half And Half Cream' 131.0 11.5 ... 4.3 4.13 0.0]
 ...
 ['Swisswurst Pork And Beef With Swiss Cheese Smoked' 307.0 27.37 ... 1.6
  0.0 0.0]
 ['Beef Variety Meats And By-Products Brain Raw' 143.0 10.3 ... 1.05 0.0
  0.0]
 ['Ceviche' 62.0 0.75 ... 3.58 1.36 0.5]]
[13  2  6 ... 13 13 10]


In [175]:
from sklearn import neighbors
neigh = KNeighborsClassifier(weights='distance', n_neighbors=6)
neigh.fit(X_train[:, [1,2,3,4,5,6]], y_train)

KNeighborsClassifier(n_neighbors=6, weights='distance')

In [176]:
neigh.score(X_test[:, [1,2,3,4,5,6]], y_test)

0.7273025237627008

In [153]:
neigh.kneighbors_graph(X[:, [1,2,3,4,5,6]])

<12202x9151 sparse matrix of type '<class 'numpy.float64'>'
	with 73212 stored elements in Compressed Sparse Row format>

In [157]:
from matplotlib.colors import ListedColormap
import seaborn as sns

# Create color maps
cmap_light = ListedColormap(['#FFAAAA', '#AAFFAA','#00AAFF'])
cmap_bold = ListedColormap(['#FF0000', '#00FF00','#00AAFF'])

cmap_light = ListedColormap(['orange', 'cyan', 'cornflowerblue'])
cmap_bold = ['darkorange', 'c', 'darkblue']

In [105]:
# we only take the first two features. We could avoid this ugly
# slicing by using a two-dim dataset
X_graph = iris.data[:, :2]
y_graph = iris.target

h = .02  # step size in the mesh

# Create color maps
cmap_light = ListedColormap(['orange', 'cyan', 'cornflowerblue'])
cmap_bold = ['darkorange', 'c', 'darkblue']

for weights in ['uniform', 'distance']:
    # we create an instance of Neighbours Classifier and fit the data.
    clf = neighbors.KNeighborsClassifier(n_neighbors, weights=weights)
    clf.fit(X, y)

    # Plot the decision boundary. For that, we will assign a color to each
    # point in the mesh [x_min, x_max]x[y_min, y_max].
    x_min, x_max = X[:, 0].min() - 1, X[:, 0].max() + 1
    y_min, y_max = X[:, 1].min() - 1, X[:, 1].max() + 1
    xx, yy = np.meshgrid(np.arange(x_min, x_max, h),
                         np.arange(y_min, y_max, h))
    Z = clf.predict(np.c_[xx.ravel(), yy.ravel()])

    # Put the result into a color plot
    Z = Z.reshape(xx.shape)
    plt.figure(figsize=(8, 6))
    plt.contourf(xx, yy, Z, cmap=cmap_light)

    # Plot also the training points
    sns.scatterplot(x=X[:, 0], y=X[:, 1], hue=iris.target_names[y],
                    palette=cmap_bold, alpha=1.0, edgecolor="black")
    plt.xlim(xx.min(), xx.max())
    plt.ylim(yy.min(), yy.max())
    plt.title("3-Class classification (k = %i, weights = '%s')"
              % (n_neighbors, weights))
    plt.xlabel(iris.feature_names[0])
    plt.ylabel(iris.feature_names[1])

plt.show()

In [106]:
neigh.predict(X_test[:, [1,2,3,4,5,6]])

array([21, 13, 13, ...,  1, 21, 17])