In [1]:
import numpy as np 
import pandas as pd

In [2]:
u1x = 0
u1y = 0
u2x = 0
u2y = 0
u3x = 0
u3y = 0

In [3]:
U = np.array([u1x, u1y, u2x, u2y, u3x, u3y])
U = U.reshape((-1,1))
U

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0]])

In [5]:
B = pd.read_csv(r'/Users/oscarbond/Documents/Bristol Year 4/FEA/Summative/Coding Answers Summative/B.csv', header= None)
B

0         1         2         3         4         5
0 -0.021839  0.000000 -0.769819  0.000000  0.791658  0.000000
1  0.000000  0.698843  0.000000 -0.365800  0.000000 -0.333042
2  0.698843 -0.021839 -0.365800 -0.769819 -0.333042  0.791658
3 -0.084163  0.000000  0.629391  0.000000 -0.545228  0.000000
4  0.000000 -0.644028  0.000000  0.468384  0.000000  0.175644
5 -0.644028 -0.084163  0.468384  0.629391  0.175644 -0.545228

In [6]:
D = pd.read_csv(r'/Users/oscarbond/Documents/Bristol Year 4/FEA/Summative/Coding Answers Summative/D.csv', header= None)
D

0           1          2
0  223.673400   82.728518   0.000000
1   82.728518  223.673400   0.000000
2    0.000000    0.000000  70.472441
3  313.383838  147.474748   0.000000
4  147.474748  313.383838   0.000000
5    0.000000    0.000000  82.954545

In [7]:
D = D.iloc[3:6, :]
D = D.to_numpy()
D

array([[313.3838384 , 147.4747475 ,   0.        ],
       [147.4747475 , 313.3838384 ,   0.        ],
       [  0.        ,   0.        ,  82.95454545]])

In [8]:
#delta = 0.9158

delta = -1.3664

In [9]:
B = B.iloc[3:6, :]
B = B.to_numpy()

#U = U.reshape((-1,1))

In [10]:
Bt = B.reshape((-1,3))
Bt

array([[-0.08416276,  0.        ,  0.6293911 ],
       [ 0.        , -0.54522834,  0.        ],
       [ 0.        , -0.6440281 ,  0.        ],
       [ 0.46838408,  0.        ,  0.17564403],
       [-0.6440281 , -0.08416276,  0.46838408],
       [ 0.6293911 ,  0.17564403, -0.54522834]])

In [11]:
BtD = np.matmul(Bt, D)
BtD

array([[ -26.37524972,  -12.41188222,   52.21085269],
       [ -80.40741133, -170.86574905,    0.        ],
       [ -94.97788187, -201.82799896,    0.        ],
       [ 146.78399927,   69.07482319,   14.5704705 ],
       [-214.23988118, -121.35313159,   38.85458804],
       [ 223.14405777,  147.86329339,  -45.22916886]])

In [12]:
BtDB = np.matmul(BtD, B)
BtDB

array([[ -31.40544253,    3.59939134,    7.85438448,   27.04751809,
          23.55105801,  -30.64690938],
       [   6.7673099 ,  110.04234423,  -50.60770914,  -80.03079582,
          43.84039916,  -30.01154841],
       [   7.99360096,  129.9829033 ,  -59.77823364,  -94.5330206 ,
          51.78463259,  -35.4498827 ],
       [ -21.73753942,  -45.7124184 ,   99.20911926,   41.52407164,
         -77.47157969,    4.18834678],
       [  -6.99242628,   74.88471765, -116.64180442,  -32.38514235,
         123.63423048,  -42.49957526],
       [  10.34843537,  -91.42150452,  119.26026178,   40.78997551,
        -129.60869693,   50.63152897]])

In [13]:
k = delta * BtDB
k

array([[  42.91239667,   -4.91820833,  -10.73223096,  -36.95772871,
         -32.18016567,   41.87593697],
       [  -9.24685225, -150.36185916,   69.15037378,  109.35407941,
         -59.90352141,   41.00777975],
       [ -10.92245635, -177.60863907,   81.68097845,  129.16991935,
         -70.75852196,   48.43871972],
       [  29.70217386,   62.4614485 , -135.55934055,  -56.73849149,
         105.85716649,   -5.72295704],
       [   9.55445127, -102.32247819,  159.37936155,   44.2510585 ,
        -168.93381253,   58.07141964],
       [ -14.1401021 ,  124.91834378, -162.95722169,  -55.73542254,
         177.09732348,  -69.18292118]])

In [14]:
k.shape

(6, 6)

In [106]:
pd.DataFrame(k).to_csv("osc_stiffness_matrix.csv")

In [18]:
u1x = -0.002775
u1y = 0.001096
u = np.array([u1x, u1y, 0, 0, 0, 0])

u

array([-0.002775,  0.001096,  0.      ,  0.      ,  0.      ,  0.      ])

In [19]:
F = np.matmul(k, u)
F

array([-0.12447226, -0.13913658, -0.16434925, -0.01396578, -0.13865904,
        0.17614929])

In [20]:
F = np.array([118.4, 141.4, 0, 0, 0, 0])
F

array([118.4, 141.4,   0. ,   0. ,   0. ,   0. ])

In [21]:
k_inv = np.linalg.inv(k)
k_inv

array([[-7.22962230e+13,  1.25718852e+14, -1.17926111e+14,
         7.60174561e+13,  4.42853450e+13, -2.09234115e+13],
       [ 1.99066214e+13,  1.85940789e+14, -1.55372627e+14,
        -2.24056656e+13, -2.17691377e+13, -2.93948108e+12],
       [ 4.71751540e+13,  7.11630990e+13, -4.81336294e+13,
        -4.35400057e+13,  1.04798545e+13,  4.94337422e+13],
       [-1.85808020e+13,  2.03515796e+14, -1.77856111e+14,
         1.61094899e+13, -1.08787783e+13, -2.56048729e+13],
       [ 6.56170444e+13,  6.27417414e+13, -3.73602935e+13,
        -6.19951844e+13,  5.26155736e+12,  6.02942425e+13],
       [ 1.22539751e+14,  1.39074102e+14, -9.54166701e+13,
        -1.25112747e+14, -5.08100960e+13,  5.75015638e+13]])

In [22]:
u = np.matmul(k_inv, F)
u

array([9.21677280e+15, 2.86489715e+16, 1.56480004e+16, 2.65771666e+16,
       1.66407403e+16, 3.41737845e+16])