In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn

In [2]:
data = pd.read_excel('https://www.myfooddata.com/spreadsheets/MyFoodData-Nutrition-Facts-SpreadSheet-Release-1-4.xlsx', header=3, usecols="B:I", engine = 'openpyxl')
data

name   Food Group  \
0      Pillsbury Golden Layer Buttermilk Biscuits Art...  Baked Foods   
1      Pillsbury Cinnamon Rolls With Icing Refrigerat...  Baked Foods   
2      Kraft Foods Shake N Bake Original Recipe Coati...  Baked Foods   
3          George Weston Bakeries Thomas English Muffins  Baked Foods   
4                Waffles Buttermilk Frozen Ready-To-Heat  Baked Foods   
...                                                  ...          ...   
14159                 Cheese As Ingredient In Sandwiches          NaN   
14160           Breading Or Batter As Ingredient In Food          NaN   
14161            Wheat Bread As Ingredient In Sandwiches          NaN   
14162                  Sauce As Ingredient In Hamburgers          NaN   
14163               Industrial Oil As Ingredient In Food          NaN   

       Calories  Fat (g)  Protein (g)  Carbohydrate (g)  Sugars (g)  Fiber (g)  
0         307.0    13.24         5.88             41.18        5.88        1.2  
1         330.0    11.27         4.34             53.42       21.34        1.4  
2         377.0     3.70         6.10             79.80         NaN        NaN  
3         232.0     1.80         8.00             46.00         NaN        NaN  
4         273.0     9.22         6.58             41.05        4.30        2.2  
...         ...      ...          ...               ...         ...        ...  
14159     359.0    28.73        20.65              4.57        2.40        0.0  
14160     201.0     1.39         6.32             39.64        0.68        1.6  
14161     263.0     3.96        11.45             45.29        5.18        5.4  
14162     271.0    22.85         1.29             17.19       13.02        0.6  
14163     892.0   100.00         0.00              0.00        0.00        0.0  

[14164 rows x 8 columns]

In [3]:
#drop any row where at least one element is missing
data_clean = data.dropna()
data_clean

name   Food Group  \
0      Pillsbury Golden Layer Buttermilk Biscuits Art...  Baked Foods   
1      Pillsbury Cinnamon Rolls With Icing Refrigerat...  Baked Foods   
4                Waffles Buttermilk Frozen Ready-To-Heat  Baked Foods   
5         Waffle Buttermilk Frozen Ready-To-Heat Toasted  Baked Foods   
6      Waffle Buttermilk Frozen Ready-To-Heat Microwaved  Baked Foods   
...                                                  ...          ...   
14154  Nutritional Drink Or Shake Ready-To-Drink Ligh...    Beverages   
14155  Nutritional Drink Or Shake High Protein Ready-...    Beverages   
14156  Nutritional Drink Or Shake High Protein Ready-...    Beverages   
14157  Nutritional Powder Mix (Kellogg's Special K20 ...   Baby Foods   
14158              Fluid Replacement 5% Glucose In Water    Beverages   

       Calories  Fat (g)  Protein (g)  Carbohydrate (g)  Sugars (g)  Fiber (g)  
0         307.0    13.24         5.88             41.18        5.88        1.2  
1         330.0    11.27         4.34             53.42       21.34        1.4  
4         273.0     9.22         6.58             41.05        4.30        2.2  
5         309.0     9.49         7.42             48.39        4.41        2.6  
6         289.0     9.40         6.92             44.16        4.50        2.4  
...         ...      ...          ...               ...         ...        ...  
14154      38.0     1.15         4.78              2.10        0.38        0.2  
14155      58.0     2.88         6.59              0.85        0.60        0.4  
14156      58.0     2.88         6.59              0.85        0.60        0.4  
14157     380.0     0.60        35.20             58.40        2.00       37.5  
14158      18.0     0.00         0.00              5.00        4.64        0.0  

[12202 rows x 8 columns]

In [4]:
#get rid of any duplicates
#removes duplicate rows based on all columns
data_clean = data_clean.drop_duplicates()
data_clean

name   Food Group  \
0      Pillsbury Golden Layer Buttermilk Biscuits Art...  Baked Foods   
1      Pillsbury Cinnamon Rolls With Icing Refrigerat...  Baked Foods   
4                Waffles Buttermilk Frozen Ready-To-Heat  Baked Foods   
5         Waffle Buttermilk Frozen Ready-To-Heat Toasted  Baked Foods   
6      Waffle Buttermilk Frozen Ready-To-Heat Microwaved  Baked Foods   
...                                                  ...          ...   
14154  Nutritional Drink Or Shake Ready-To-Drink Ligh...    Beverages   
14155  Nutritional Drink Or Shake High Protein Ready-...    Beverages   
14156  Nutritional Drink Or Shake High Protein Ready-...    Beverages   
14157  Nutritional Powder Mix (Kellogg's Special K20 ...   Baby Foods   
14158              Fluid Replacement 5% Glucose In Water    Beverages   

       Calories  Fat (g)  Protein (g)  Carbohydrate (g)  Sugars (g)  Fiber (g)  
0         307.0    13.24         5.88             41.18        5.88        1.2  
1         330.0    11.27         4.34             53.42       21.34        1.4  
4         273.0     9.22         6.58             41.05        4.30        2.2  
5         309.0     9.49         7.42             48.39        4.41        2.6  
6         289.0     9.40         6.92             44.16        4.50        2.4  
...         ...      ...          ...               ...         ...        ...  
14154      38.0     1.15         4.78              2.10        0.38        0.2  
14155      58.0     2.88         6.59              0.85        0.60        0.4  
14156      58.0     2.88         6.59              0.85        0.60        0.4  
14157     380.0     0.60        35.20             58.40        2.00       37.5  
14158      18.0     0.00         0.00              5.00        4.64        0.0  

[12202 rows x 8 columns]

In [5]:
#re-number index
data_clean = data_clean.reset_index()
data_clean

index                                               name   Food Group  \
0          0  Pillsbury Golden Layer Buttermilk Biscuits Art...  Baked Foods   
1          1  Pillsbury Cinnamon Rolls With Icing Refrigerat...  Baked Foods   
2          4            Waffles Buttermilk Frozen Ready-To-Heat  Baked Foods   
3          5     Waffle Buttermilk Frozen Ready-To-Heat Toasted  Baked Foods   
4          6  Waffle Buttermilk Frozen Ready-To-Heat Microwaved  Baked Foods   
...      ...                                                ...          ...   
12197  14154  Nutritional Drink Or Shake Ready-To-Drink Ligh...    Beverages   
12198  14155  Nutritional Drink Or Shake High Protein Ready-...    Beverages   
12199  14156  Nutritional Drink Or Shake High Protein Ready-...    Beverages   
12200  14157  Nutritional Powder Mix (Kellogg's Special K20 ...   Baby Foods   
12201  14158              Fluid Replacement 5% Glucose In Water    Beverages   

       Calories  Fat (g)  Protein (g)  Carbohydrate (g)  Sugars (g)  Fiber (g)  
0         307.0    13.24         5.88             41.18        5.88        1.2  
1         330.0    11.27         4.34             53.42       21.34        1.4  
2         273.0     9.22         6.58             41.05        4.30        2.2  
3         309.0     9.49         7.42             48.39        4.41        2.6  
4         289.0     9.40         6.92             44.16        4.50        2.4  
...         ...      ...          ...               ...         ...        ...  
12197      38.0     1.15         4.78              2.10        0.38        0.2  
12198      58.0     2.88         6.59              0.85        0.60        0.4  
12199      58.0     2.88         6.59              0.85        0.60        0.4  
12200     380.0     0.60        35.20             58.40        2.00       37.5  
12201      18.0     0.00         0.00              5.00        4.64        0.0  

[12202 rows x 9 columns]

In [6]:
#get rid of column called index
data_clean = data_clean.drop(columns=['index'])
data_clean

name   Food Group  \
0      Pillsbury Golden Layer Buttermilk Biscuits Art...  Baked Foods   
1      Pillsbury Cinnamon Rolls With Icing Refrigerat...  Baked Foods   
2                Waffles Buttermilk Frozen Ready-To-Heat  Baked Foods   
3         Waffle Buttermilk Frozen Ready-To-Heat Toasted  Baked Foods   
4      Waffle Buttermilk Frozen Ready-To-Heat Microwaved  Baked Foods   
...                                                  ...          ...   
12197  Nutritional Drink Or Shake Ready-To-Drink Ligh...    Beverages   
12198  Nutritional Drink Or Shake High Protein Ready-...    Beverages   
12199  Nutritional Drink Or Shake High Protein Ready-...    Beverages   
12200  Nutritional Powder Mix (Kellogg's Special K20 ...   Baby Foods   
12201              Fluid Replacement 5% Glucose In Water    Beverages   

       Calories  Fat (g)  Protein (g)  Carbohydrate (g)  Sugars (g)  Fiber (g)  
0         307.0    13.24         5.88             41.18        5.88        1.2  
1         330.0    11.27         4.34             53.42       21.34        1.4  
2         273.0     9.22         6.58             41.05        4.30        2.2  
3         309.0     9.49         7.42             48.39        4.41        2.6  
4         289.0     9.40         6.92             44.16        4.50        2.4  
...         ...      ...          ...               ...         ...        ...  
12197      38.0     1.15         4.78              2.10        0.38        0.2  
12198      58.0     2.88         6.59              0.85        0.60        0.4  
12199      58.0     2.88         6.59              0.85        0.60        0.4  
12200     380.0     0.60        35.20             58.40        2.00       37.5  
12201      18.0     0.00         0.00              5.00        4.64        0.0  

[12202 rows x 8 columns]

## NOW DOING KNN

In [25]:
# y is the list of food groups 
y = data_clean.iloc[:, 1].values

# x is the labels and nutritional values 
X = data_clean.iloc[:, 2:].values

print(X)
print(y)

[[307.    13.24   5.88  41.18   5.88   1.2 ]
 [330.    11.27   4.34  53.42  21.34   1.4 ]
 [273.     9.22   6.58  41.05   4.3    2.2 ]
 ...
 [ 58.     2.88   6.59   0.85   0.6    0.4 ]
 [380.     0.6   35.2   58.4    2.    37.5 ]
 [ 18.     0.     0.     5.     4.64   0.  ]]
['Baked Foods' 'Baked Foods' 'Baked Foods' ... 'Beverages' 'Baby Foods'
 'Beverages']


In [26]:
import operator
from pprint import pprint #short for pretty print

def knn(X, y, test_point, k):
    distances = [] #empty list (keeping track of distances and class in a list)
    for i in range(len(X)):
        distance = np.linalg.norm(X[i] - test_point) #keeping track of the distances
        distances.append((y[i], X[i], distance)) #this keeps track of 
        #(label, data point, distance of that data point to that test point)
    
    distances.sort(key=operator.itemgetter(2)) #sort our list of distances by 3rd element element 
    #list of tuples, sorting a list of something more complicated than numbers
    #sorted distance with smallest distance at the top of the list.
    
    #now we want to find the most frequent label,(ie y[i]), in the k nearest neighbours
   
    nn_labels = [] #list to keep track of this
    for nn in distances[:k]: #iterate over first k distances (ie k smallest distances from testpoint)
        nn_labels.append(nn[0]) #append to list the label y[i] for element
        #iteration means in end we get a list of labels of each element in these first k distances
    
    from statistics import mode
    y_hat = mode(nn_labels) #most common element of this list 
    #ie most common label for the the k nearest neighbours
    
    
    print("Test point: "+str(test_point))
    print("Closest K neighbours")
    pprint(distances[:k]) #using pprint to print clearer
    print("Furtherest K neighbours")
    pprint(distances[-k:]) #furthest k distances away, from -k to end of array
    
    return y_hat    
    


In [19]:
#elementidx = data_clean[5][0]
#this doesnt work but i dont understand why not??

In [27]:
#testing on data point to see if its catagorised right
idx = 3000

test_point = X[idx]
test_point_label = y[idx]

X = np.delete(X, idx, axis=0) 
#cardinal sin to train on testing set so delete this x from testing set X
#delete row from x so not training on dataset

In [28]:
#test where now 
y_hat = knn(X, y, test_point, 1) #1 nearest neighbours
print("Prediction for elementidx","is: "+str(y_hat))
print("Actual: "+str(y[idx]))

Test point: [177.     6.71  27.29   0.     0.     0.  ]
Closest K neighbours
[('Meats',
  array([177.  ,   6.78,  27.12,   0.  ,   0.  ,   0.  ]),
  0.18384776310850076)]
Furtherest K neighbours
[('Fats and Oils',
  array([902., 100.,   0.,   0.,   0.,   0.]),
  731.4866835424963)]
Prediction for elementidx is: Meats
Actual: Meats


I want it to say prediction for 'element idx with 5' is... but for some reason the data[5][0] thing isnt working although it worked when i practiced knn

In [29]:
#test where now 
y_hat = knn(X, y, test_point, 3) #3 nearest neighbours
print("Prediction: "+str(y_hat))
print("Actual: "+str(y[idx]))

Test point: [177.     6.71  27.29   0.     0.     0.  ]
Closest K neighbours
[('Meats',
  array([177.  ,   6.78,  27.12,   0.  ,   0.  ,   0.  ]),
  0.18384776310850076),
 ('Meats',
  array([177.  ,   6.48,  27.76,   0.  ,   0.  ,   0.  ]),
  0.5232590180780471),
 ('Meats',
  array([177.  ,   7.49,  27.51,   0.  ,   0.  ,   0.  ]),
  0.8104319835741933)]
Furtherest K neighbours
[('Baby Foods', array([900., 100.,   0.,   0.,   0.,   0.]), 729.5044675668546),
 ('Fats and Oils',
  array([902., 100.,   0.,   0.,   0.,   0.]),
  731.4866835424963),
 ('Fats and Oils',
  array([902., 100.,   0.,   0.,   0.,   0.]),
  731.4866835424963)]
Prediction: Meats
Actual: Meats


In [30]:
#test where now 
y_hat = knn(X, y, test_point, 10) #10 nearest neighbours
print("Prediction: "+str(y_hat))
print("Actual: "+str(y[idx]))

Test point: [177.     6.71  27.29   0.     0.     0.  ]
Closest K neighbours
[('Meats',
  array([177.  ,   6.78,  27.12,   0.  ,   0.  ,   0.  ]),
  0.18384776310850076),
 ('Meats',
  array([177.  ,   6.48,  27.76,   0.  ,   0.  ,   0.  ]),
  0.5232590180780471),
 ('Meats',
  array([177.  ,   7.49,  27.51,   0.  ,   0.  ,   0.  ]),
  0.8104319835741933),
 ('Meats',
  array([176.  ,   6.42,  27.68,   0.  ,   0.  ,   0.  ]),
  1.1118453129819816),
 ('Meats',
  array([177.  ,   7.2 ,  26.22,   0.  ,   0.  ,   0.  ]),
  1.1768602295939823),
 ('Meats',
  array([176.  ,   6.94,  26.66,   0.  ,   0.  ,   0.  ]),
  1.2040764095355405),
 ('Meats',
  array([178.  ,   6.48,  27.96,   0.  ,   0.  ,   0.  ]),
  1.2254794979925212),
 ('Meats',
  array([177.  ,   6.14,  28.41,   0.  ,   0.  ,   0.  ]),
  1.2567020331009267),
 ('Meats',
  array([178.  ,   7.58,  27.51,   0.  ,   0.  ,   0.  ]),
  1.3436145280548293),
 ('Meats',
  array([177.  ,   7.36,  26.  ,   0.  ,   0.  ,   0.  ]),
  1.44450683625

In [31]:
y_hat = knn(X, y, test_point, 500) #500 nearest neighbours
print("Prediction: "+str(y_hat))
print("Actual: "+str(y[idx]))

Test point: [177.     6.71  27.29   0.     0.     0.  ]
Closest K neighbours
[('Meats',
  array([177.  ,   6.78,  27.12,   0.  ,   0.  ,   0.  ]),
  0.18384776310850076),
 ('Meats',
  array([177.  ,   6.48,  27.76,   0.  ,   0.  ,   0.  ]),
  0.5232590180780471),
 ('Meats',
  array([177.  ,   7.49,  27.51,   0.  ,   0.  ,   0.  ]),
  0.8104319835741933),
 ('Meats',
  array([176.  ,   6.42,  27.68,   0.  ,   0.  ,   0.  ]),
  1.1118453129819816),
 ('Meats',
  array([177.  ,   7.2 ,  26.22,   0.  ,   0.  ,   0.  ]),
  1.1768602295939823),
 ('Meats',
  array([176.  ,   6.94,  26.66,   0.  ,   0.  ,   0.  ]),
  1.2040764095355405),
 ('Meats',
  array([178.  ,   6.48,  27.96,   0.  ,   0.  ,   0.  ]),
  1.2254794979925212),
 ('Meats',
  array([177.  ,   6.14,  28.41,   0.  ,   0.  ,   0.  ]),
  1.2567020331009267),
 ('Meats',
  array([178.  ,   7.58,  27.51,   0.  ,   0.  ,   0.  ]),
  1.3436145280548293),
 ('Meats',
  array([177.  ,   7.36,  26.  ,   0.  ,   0.  ,   0.  ]),
  1.44450683625

  array([1.830e+02, 1.138e+01, 2.009e+01, 9.000e-02, 0.000e+00, 0.000e+00]),
  10.471723831346967),
 ('Meats',
  array([184.  ,  10.68,  20.56,   0.  ,   0.  ,   0.  ]),
  10.490652982536407),
 ('Meats',
  array([171.  ,  10.26,  19.45,   0.  ,   0.  ,   0.  ]),
  10.491334519497507),
 ('Meats',
  array([167.  ,   4.46,  29.66,   0.  ,   0.  ,   0.  ]),
  10.520427747957779),
 ('Meats',
  array([187.  ,   7.15,  30.55,   0.  ,   0.  ,   0.  ]),
  10.527164860493068),
 ('Meats',
  array([167.  ,   4.42,  29.77,   0.  ,   0.  ,   0.  ]),
  10.554359288938386),
 ('Meats',
  array([168.  ,   8.19,  21.94,   0.  ,   0.  ,   0.  ]),
  10.574161905323749),
 ('Meats',
  array([187.  ,   7.02,  30.87,   0.  ,   0.  ,   0.  ]),
  10.626029361901839),
 ('Meats',
  array([167.  ,   4.28,  29.96,   0.  ,   0.  ,   0.  ]),
  10.631735512135355),
 ('Fish',
  array([171.  ,   1.91,  29.21,   7.11,   0.  ,   0.  ]),
  10.643237289471658),
 ('Fish',
  array([167.  ,   7.39,  23.59,   0.  ,   0.  ,   0. 

  15.35257633102666),
 ('Fish',
  array([179.  ,   4.55,  20.03,  13.14,   1.17,   0.6 ]),
  15.354533532478282)]
Furtherest K neighbours
[('Nuts and Seeds',
  array([500.  ,  35.71,   8.28,  47.59,  32.14,   3.6 ]),
  329.91230319586447),
 ('Sweets',
  array([492.  ,  21.13,   4.33,  71.19,  63.68,   2.8 ]),
  330.28941324238656),
 ('Soups and Sauces',
  array([503.  ,  50.89,   1.09,  10.05,   8.98,   1.  ]),
  330.29828231463756),
 ('Sweets',
  array([497.  ,  24.77,  12.46,  59.86,  53.25,   3.  ]),
  330.7172124338254),
 ('Nuts and Seeds',
  array([501.  ,  32.2 ,  11.62,  48.31,  34.12,   5.9 ]),
  330.76295061569397),
 ('Snacks',
  array([501.  ,  24.63,   7.19,  62.74,   3.03,   4.  ]),
  331.15347635197793),
 ('Snacks',
  array([501.  ,  25.61,   7.  ,  62.68,   1.77,   3.3 ]),
  331.1913335218783),
 ('Soups and Sauces',
  array([5.040e+02, 5.422e+01, 4.680e+00, 1.520e+00, 3.800e-01, 0.000e+00]),
  331.2097024545024),
 ('Meats',
  array([505.  ,  50.17,  11.16,   2.11,   0.  ,

 ('Snacks',
  array([558.  ,  35.76,   5.76,  54.1 ,   2.76,   2.2 ]),
  386.5329365008886),
 ('Meats',
  array([560.  ,  57.22,   7.9 ,   3.39,   0.  ,   0.  ]),
  386.8174301915569),
 ('Snacks',
  array([5.590e+02, 3.532e+01, 6.710e+00, 5.343e+01, 3.400e-01, 4.200e+00]),
  387.3481496018795),
 ('Snacks',
  array([5.590e+02, 3.532e+01, 6.710e+00, 5.343e+01, 3.400e-01, 4.200e+00]),
  387.3481496018795),
 ('Sweets',
  array([560.  ,  48.77,   7.29,  31.86,  25.12,   6.5 ]),
  388.00305101893207),
 ('Sweets',
  array([556.  ,  32.4 ,   5.54,  60.49,  47.56,   6.5 ]),
  388.24899523372886),
 ('Snacks',
  array([5.600e+02, 3.539e+01, 6.720e+00, 5.354e+01, 3.400e-01, 4.200e+00]),
  388.35416117250503),
 ('Snacks',
  array([560.  ,  36.01,   5.85,  53.53,   3.19,   1.4 ]),
  388.43887627270266),
 ('Snacks',
  array([560.  ,  36.01,   5.85,  53.53,   3.19,   1.4 ]),
  388.43887627270266),
 ('Beans and Lentils',
  array([563.  ,  48.75,  25.19,  16.54,   3.95,   8.5 ]),
  388.7533867376592),
 

 ('Fats and Oils',
  array([884., 100.,   0.,   0.,   0.,   0.]),
  713.6503122678502),
 ('Fats and Oils',
  array([884., 100.,   0.,   0.,   0.,   0.]),
  713.6503122678502),
 ('Fats and Oils',
  array([884., 100.,   0.,   0.,   0.,   0.]),
  713.6503122678502),
 ('Fats and Oils',
  array([884., 100.,   0.,   0.,   0.,   0.]),
  713.6503122678502),
 ('Fats and Oils',
  array([884., 100.,   0.,   0.,   0.,   0.]),
  713.6503122678502),
 ('Fats and Oils',
  array([884., 100.,   0.,   0.,   0.,   0.]),
  713.6503122678502),
 ('Fats and Oils',
  array([884., 100.,   0.,   0.,   0.,   0.]),
  713.6503122678502),
 ('Fats and Oils',
  array([884., 100.,   0.,   0.,   0.,   0.]),
  713.6503122678502),
 ('Fats and Oils',
  array([884., 100.,   0.,   0.,   0.,   0.]),
  713.6503122678502),
 ('Fats and Oils',
  array([884., 100.,   0.,   0.,   0.,   0.]),
  713.6503122678502),
 ('Fats and Oils',
  array([884., 100.,   0.,   0.,   0.,   0.]),
  713.6503122678502),
 ('Fats and Oils',
  array([884.